baseURL = "https://chunkstories.xyz/"
languageCode = "en-us"
title = "Chunk Stories"
theme = "robotico"

# menu
[[languages.en.menu.primary]]
name = "home"
url = "/"
weight = 10 

[[languages.en.menu.primary]]
name = "code"
url = "https://github.com/Hugobros3/chunkstories"

[[languages.en.menu.primary]]
name = "talk"
url = "https://discord.gg/wudd4pe"

[[languages.en.menu.primary]]
name = "docs"
url = "/docs"

[[languages.en.menu.primary]]
name = "blog"
url = "/blog"

[[languages.en.menu.primary]]
name = "pics"
url = "/pics"

[markup]
  [markup.highlight]
    style = "github"
    tabWidth = 4